////////////////////////////////////////////////////////////////////////////////////////////////////
//                               This file is part of CosmoScout VR                               //
////////////////////////////////////////////////////////////////////////////////////////////////////

// SPDX-FileCopyrightText: German Aerospace Center (DLR) <cosmoscout@dlr.de>
// SPDX-License-Identifier: MIT

layout(local_size_x = 256) in;

layout(r32ui, binding = 0) coherent uniform uimage2D uOutImage;

// input SSBO
struct Star {
  float posX;
  float posY;
  float posZ;
  float tEff;
  float absMagnitude;
};

// This SSBO contains all stars. In the other modes, this is bound as VBO.
layout(std430, binding = 0) buffer StarSSBO {
  Star stars[];
};

layout(std430, binding = 4) buffer GpuProfilingSSBO {
  uint debugSSBO_starsDrawn;
};

// uniforms
uniform int   uStarCount;
uniform mat4  uMatMV;
uniform mat4  uMatP;
uniform mat4  uInvMV;
uniform mat4  uInvP;
uniform vec2  uResolution;
uniform float uMinMagnitude;
uniform float uMaxMagnitude;
uniform float uSolidAngle;

/*const uint BLIT32_WIDTH   = 5u;
const uint BLIT32_HEIGHT  = 6u;
const uint BLIT32_ADVANCE = 6u; 

const uint blit32_Glyphs[95] = uint[](
        //ASCII space
		0x00000000,0x08021084,0x0000294a,0x15f52bea,0x08fa38be,0x33a22e60,0x2e94d8a6,0x00001084,
        0x10421088,0x04421082,0x00a23880,0x00471000,0x04420000,0x00070000,0x0c600000,0x02222200,
        //ASCII 0
        0x1d3ad72e,0x3e4214c4,0x3e22222e,0x1d18320f,0x210fc888,0x1d183c3f,0x1d17844c,0x0222221f,
        //ASCII 8
        0x1d18ba2e,0x1f0f462e,0x0c6018c0,0x04401000,0x10411100,0x00e03800,0x04441040,0x0802322e,
        0x3c1ef62e,0x231fc544,0x1f18be2f,0x3c10862e,0x1f18c62f,0x3e10bc3f,0x0210bc3f,0x1d1c843e,
        0x2318fe31,0x3e42109f,0x0c94211f,0x23149d31,0x3e108421,0x231ad6bb,0x239cd671,0x1d18c62e,
        0x0217c62f,0x30eac62e,0x2297c62f,0x1d141a2e,0x0842109f,0x1d18c631,0x08454631,0x375ad631,
        0x22a21151,0x08421151,0x3e22221f,0x1842108c,0x20820820,0x0c421086,0x00004544,0xbe000000,
        0x00000082,0x1c97b000,0x0e949c21,0x1c10b800,0x1c94b908,0x3c1fc5c0,0x42211c4c,0x4e87252e,
        0x12949c21,0x0c210040,0x8c421004,0x12519521,0x0c210842,0x235aac00,0x12949c00,0x0c949800,
        0x4213a526,0x7087252e,0x02149800,0x0e837000,0x0c213c42,0x0e94a400,0x0464a400,0x155ac400,
        0x36426c00,0x4e872529,0x1e223c00,0x1843188c,0x08421084,0x0c463086,0x0006d800
);

// --- draw a single ASCII character using blit32 ---
void drawChar(uint ascii, ivec2 pos, vec4 color) {
    if (ascii < 32u || ascii > 126u) return;
    uint glyph = blit32_Glyphs[ascii - 32u];

    for (int gy = 0; gy < int(BLIT32_HEIGHT); gy++) {
        for (int gx = 0; gx < int(BLIT32_WIDTH); gx++) {
            uint shift = uint(gy) * BLIT32_WIDTH + uint(gx);
            uint bit   = (glyph >> shift) & 1u;
            if (bit != 0u) {
                imageAtomicExchange(uOutImage, pos + ivec2(gx, BLIT32_HEIGHT - gy), packHalf2x16(vec2(100.0, 10000.0)));
            }
        }
    }
}

// --- print int in decimal or hex, controlled by hexMode ---
void drawInt(int n, ivec2 pos, bool hexMode) {
    vec4 color = vec4(1.0);

    uint v = uint(abs(n));
    uint digits[16];
    int  count = 0;

    if (v == 0u) {
        drawChar(48u, pos, color); // '0'
        return;
    }

    if (!hexMode) {
        while (v > 0u && count < 10) {
            digits[count++] = 48u + (v % 10u); // '0' + digit
            v /= 10u;
        }
    } else {
        while (v > 0u && count < 8) {
            uint nib = v & 0xFu;
            digits[count++] = (nib < 10u)
                ? (48u + nib)      // '0'..'9'
                : (55u + nib);     // 'A'..'F' (55 = 'A' - 10)
            v >>= 4;
        }
    }

    if(n < 0 && !hexMode) drawChar(45, pos - ivec2(BLIT32_ADVANCE, 0), color); //minus sign if negative

    for (int i = count - 1; i >= 0; --i) {
        drawChar(digits[i], pos, color);
        pos.x += int(BLIT32_ADVANCE);
    }
}

void main() {
  int index = int(gl_GlobalInvocationID.x);

  // Discard any threads outside our star data.
  if (index >= uStarCount) {
    return;
  }

  Star star            = stars[index];
  vec3 inPos           = vec3(star.posX, star.posY, star.posZ);

  //if(length(inPos) > 250.0) return;

  vec4 vScreenSpacePos = uMatP * uMatMV * vec4(inPos * cParsecToMeter, 1);

  // Discard stars behind the camera.
  if (vScreenSpacePos.w <= 0) {
    return;
  }

  vScreenSpacePos /= vScreenSpacePos.w;

  // Discard stars outside the frustum.
  if (vScreenSpacePos.x < -1 || vScreenSpacePos.x > 1 || vScreenSpacePos.y < -1 ||
      vScreenSpacePos.y > 1) {
    return;
  }

  vec3  observerPos = getObserverPosition(uInvMV);
  float vMagnitude  = getApparentMagnitude(star.absMagnitude, length(inPos - observerPos));

  // Discard stars outside the magnitude range.
  /*if (vMagnitude > uMaxMagnitude || vMagnitude < uMinMagnitude) {
    return;
  }*/

  float solidAngle = getSolidAngleOfPixel(vScreenSpacePos, uResolution, uInvP);
  float luminance  = magnitudeToLuminance(vMagnitude, solidAngle);
  //if(length(inPos + 50.0) < 25.0) luminance = 1.0;

  // Compute the star coordinates in fractional pixel coordinates.
  // Shift the exact projected star coordinates by -.5 such that one refers to the four nearest
  // pixels in the following.
  ivec2 outSize           = imageSize(uOutImage);
  vec2  starCoords        = ((vScreenSpacePos.xy + 1) / 2) * vec2(outSize) - 0.5;
  ivec2 integerStarCoords = ivec2(floor(starCoords));

  // Compute the fractional part of the star coordinates.
  vec2 starWeights = fract(starCoords);

  // Four nearest pixels.
  ivec2 targetStarCoords[4] = {integerStarCoords, integerStarCoords + ivec2(1, 0),
      integerStarCoords + ivec2(0, 1), integerStarCoords + ivec2(1, 1)};

  // Linear interpolation weights for the four nearest pixels.
  float weights[4] = {(1 - starWeights.x) * (1 - starWeights.y),
      starWeights.x * (1 - starWeights.y), (1 - starWeights.x) * starWeights.y,
      starWeights.x * starWeights.y};

  // Write the contribution of the star to the four nearest pixels.
  for (int i = 0; i < 4; ++i) {
    float oPixelWeightedLuminance = weights[i] * luminance;

    // We use an atomic operation to write the new luminance and color temperature to the image. The
    // process is as follows: We read the old value from the image, compute the new value, and write
    // the result only if the image still contains the old value. Else another thread has already
    // written a new value, and we have to try again.
    uint oldVal = 0;
    uint newVal = 0;

    do {
      oldVal = imageLoad(uOutImage, targetStarCoords[i]).r;

      // Unpack the old value.
      vec2 temperatureLuminance = unpackHalf2x16(oldVal);

      // Luminance is additive.
      float newLuminance = temperatureLuminance.y + oPixelWeightedLuminance;

      // Weighted average of color temperature.
      float newTEff =
          (temperatureLuminance.x * temperatureLuminance.y + star.tEff * oPixelWeightedLuminance) /
          newLuminance;

      // Pack the new value.
      newVal = packHalf2x16(vec2(newTEff, newLuminance));

    } while (oldVal != imageAtomicCompSwap(uOutImage, targetStarCoords[i], oldVal, newVal));
  }
  //drawInt(int(star.tEff), integerStarCoords + ivec2(10, 10), false);
  //drawInt(int(star.absMagnitude * 1000.0), integerStarCoords + ivec2(10, 16), false);
  //atomicAdd(debugSSBO_starsDrawn, 1u);
}